# Generated by Django 5.0 on 2024-01-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_class_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
