# Generated by Django 5.0 on 2024-01-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_gradingconfig_student_user_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingconfig",
            name="points",
            field=models.CharField(default="add points", max_length=200),
        ),
        migrations.AddField(
            model_name="gradingconfig",
            name="row",
            field=models.CharField(default="add row", max_length=200),
        ),
        migrations.AddField(
            model_name="gradingconfig",
            name="standard",
            field=models.CharField(default="add standard", max_length=200),
        ),
    ]
