# Generated by Django 5.0 on 2024-01-16 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_gradingconfig_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sheet_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
