# Generated by Django 5.0 on 2024-01-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_userprofile_sheet_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="sheet_name",
            new_name="google_sheet_name",
        ),
    ]
