# Generated by Django 5.0 on 2024-01-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_alter_gradingconfig_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradingconfig",
            name="user",
        ),
    ]
