# Generated by Django 5.0 on 2024-01-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_alter_userprofile_json_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="json_file",
            field=models.FileField(upload_to="documents/%Y/%m/%d"),
        ),
    ]
