# Generated by Django 5.0 on 2024-01-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0016_alter_userprofile_json_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradingconfig",
            name="points",
            field=models.CharField(
                blank=True, default="Points", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gradingconfig",
            name="row",
            field=models.CharField(
                blank=True, default="Row", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gradingconfig",
            name="standard",
            field=models.CharField(
                blank=True, default="Standard", max_length=200, null=True
            ),
        ),
    ]
