# Generated by Django 5.0 on 2024-02-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_alter_gradingconfig_points_alter_gradingconfig_row_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.CharField(max_length=200)),
            ],
        ),
    ]
